### ISSUE TITLE
List does not show module when looking for single title.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#158]
**Describe the bug**
List does not list what I am looking for.

**To Reproduce**
1.  add n/CS2113T Tutorial d/mon st/08:00 et/09:00
2. list n/CS2113T
3. produces `0 slots listed`

**Expected behavior**
1. Lists `add n/CS2113T Tutorial d/mon st/08:00 et/09:00` this command that I have added

<hr>

**Reported by:** @nicholasleeeee
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#5]</sub>

**Comment by seanieyap** [comment]
Hi, thank you for feedback.

However, the commands input here are incorrect, as the command in item 1, "add n/CS2113T Tutorial d/mon st/08:00 et/09:00", adds slots with the name "CS2113T Tutorial" not "CS2113T". The command in item 2 should have "list n/CS2113T Tutorial"
