### ISSUE TITLE
User guide not updated with correct parameters for edit command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#159]
**Describe the bug**
Command listed in user guide is invalid. Wrong parameter was stated in sample command. 

**To Reproduce**
1. Go to 'list'
2. Execute 'edit 1 des/Topic: Sequence Diagram' as stated in User Guide

**Expected behavior**
Slot should be updated with a new description.

<hr>

**Reported by:** @josephinetanadi
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#14]</sub>

**Comment by seanieyap** [comment]
Hi, thank you for feedback.

There is indeed a typo in the user guide. The prefix for "new description" should have been "ndes/" instead of "des/". This has been fixed, coincidentally, in #157.
