### ISSUE TITLE
Invalid end time does not throw exception

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#160]
**Describe the bug**
incorrect end time does not throw an error

**To Reproduce**
1. `add n/CS2113T Tutorial d/mon st/08:00 et/0`
2. shows `1 slots added`

**Expected behavior**
`Invalid Command Format`

<hr>

**Reported by:** @nicholasleeeee
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#16]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. However, "add n/CS2113T Tutorial d/mon st/08:00 et/0" is a valid command as the prefix "et" can also be used as "duration". In the command, the duration for the slot you would like to add is set to 0.
