### ISSUE TITLE
Able to add a module with a wrong format

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#162]
**Describe the bug**
I can add a module with a wrong module code format. Like alphabet characters where numbers should be.

**To Reproduce**
1. Type 'add n/CS21dsdl13T Tutorial d/mon st/08:00 et/09:00 des/Topic: Sequence Diagram t/CS2113T t/Tutorial r/normal'
2. The module 'CS21dsdl13T' is added.

**Expected behavior**
An error invalid module format should pop up.

<hr>

**Reported by:** @jkupoluyi
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#32]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. However, this is an intended behavior, users are able to name their slots without restriction as similar to conventional planner/scheduling/calendar applications such as Microsoft outlook, Google calendar, etc. Please take note that this is not a module planning application but as stated in the user guide, caters to any activities/events that the user would like to add in.
