### ISSUE TITLE
Add command allows adding several slotsin the same time interval 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#163]
**Describe the bug**
The "Add" command allows adding two slots with the same start time and end.  

**Expected behavior**
"Add" command should not add successfully if a user adds a  slot that already exists. 

**Screenshots**
![2477f4b00dbd1e3df354a8c83c7f5be](https://user-images.githubusercontent.com/32561507/55453313-e51da680-560d-11e9-811e-6f01ea64ec5b.png)

<hr>

**Reported by:** @wanchunwei
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#42]</sub>

**Comment by seanieyap** [comment]
Hi, 

Thank you for your feedback. However, this is a correct behavior as you are able to have multiple slots in the same time slot such as in the case of conflicting meetings, clashing classes, double booked events that overlapped, etc.
