### ISSUE TITLE
`Add` is able to take in multiple tasks of the exact same details

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#164]
**Describe the bug**
Adds the slot even though it has already been added

**To Reproduce**
1. `add n/CS2113T Tutorial d/mon st/08:00 et/09:00`
2.`1 slot added`

**Expected behavior**
Slot has already been added

<hr>

**Reported by:** @nicholasleeeee
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#49]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. Yes this is an intended behavior as similar to existing calendar/scheduling/planner applications. The user are free to add any slot to any time unrestricted. For example, you can have lectures of same names across weeks and you can have two slots overlapping to accommodate conflicting meetings, double booked events that overlap, clashing classes, etc.
