### ISSUE TITLE
I can add multiple modules to the same timeslot.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#165]
**Describe the bug**
Multiple modules can be added to the same timeslot.

**To Reproduce**
1. Add a module to the timeTable: ' add n/CS2113T Tutorial d/mon st/08:00 et/09:00 des/Topic: Sequence Diagram t/CS2113T t/Tutorial r/normal '
2. Add another module in the same timeslot: add n/CS2343T Tutorial d/mon st/08:00 et/09:00 des/Topic: Sequence Diagram t/CS2113T t/Tutorial r/normal'

**Expected behavior**
An error "Module already assigned to this timeslot should pop up".

<hr>

**Reported by:** @jkupoluyi
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#60]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. However, this is an intended behavior as similar to other scheduling/planner/calendar applications like Microsoft Outlook, Google calendar, etc. Users should be able to plan their schedule however they want and multiple slots in the same time period can occur to accommodate conflicting scheduled meetings, clashing classes, double booked events, tentative activities, etc.
