### ISSUE TITLE
Better to add a new feature to  "list" command which make it can list all slots in the planner.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#166]
**Please describe the problem**
Users are not able to see all the slots in the planner, so it is better to add a function that user can list all slots they have in planner. 

<hr>

**Reported by:** @wanchunwei
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#62]</sub>

**Comment by marcus-pzj** [comment]
Thank you for your suggestion. The additional feature has been implemented in the latest PR as referenced.
