### ISSUE TITLE
Find command does not return any result

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#167]
**Describe the bug**
User guide seems to suggest that 'find n/CS' should return slots containing the name 'CS2113T Tutorial', but no slots were returned. 

**To Reproduce**
1. Execute 'add n/CS2113T Tutorial d/mon st/8:00 am et/9:00 am des/Topic: Sequence Diagram t/CS2113T t/Tutorial'
2. Execute 'find n/CS' ----> Returns 0 slots
3. Execute 'find n/CS2113' ----> Returns 0 slots
4. Execute 'find n/Tut' ----> Returns 0 slots
5. Execute 'find n/CS2113T Tutorial' ----> Returns slots

**Expected behavior**
Expected to find slots for all 3 execution of find command. 

<hr>

**Reported by:** @josephinetanadi
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#72]</sub>

**Comment by marcus-pzj** [comment]
Thank you for your bug report. A better searching algorithm has been implemented to address your issue. It has been implemented in the latest PR as referenced.
