### ISSUE TITLE
find does not find names that closely match

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#168]
**Describe the bug**
Find does not find all slots whose name closely matches CS (eg. CS2101, CS2113T, SOCSMeet)

**To Reproduce**
1. add n/CS2113T Tutorial d/mon st/08:00 et/09:00
2. find n/CS
3. `0 slots listed.`

**Expected behavior**
To show all this added slot -
n/CS2113T Tutorial d/mon st/08:00 et/09:00

**Screenshots**
<img width="322" alt="Screen Shot 2019-04-03 at 12 47 44 PM" src="https://user-images.githubusercontent.com/35677197/55453545-f0bd9d00-560e-11e9-9e12-4e0354af0e30.png">
<img width="195" alt="Screen Shot 2019-04-03 at 12 48 15 PM" src="https://user-images.githubusercontent.com/35677197/55453546-f1563380-560e-11e9-8959-ba029c4f3d47.png">

<hr>

**Reported by:** @nicholasleeeee
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#79]</sub>

**Comment by marcus-pzj** [comment]
Thank you for your bug report. A better searching algorithm has been implemented to address your issue. It has been implemented in the latest PR as referenced.
