### ISSUE TITLE
Add command allows adding identical slots

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#169]
**Describe the bug**
Add command allows adding slots with the exact same details multiple times. Not sure if this is an intended feature, but it confuses the readers especially when listing slots with that same name.

**To Reproduce**
1. Execute 'add n/CS2113T Tutorial d/mon st/8:00 am et/9:00 am des/Topic: Sequence Diagram t/CS2113T t/Tutorial'
2. Execute 'add n/CS2113T Tutorial d/mon st/8:00 am et/9:00 am des/Topic: Sequence Diagram t/CS2113T t/Tutorial'
3. Execute 'list n/CS2113T Tutorial'

**Expected behavior**
Error message preventing users from adding identical slots. 

<hr>

**Reported by:** @josephinetanadi
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#99]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. Yes this is an intended behavior as similar to existing calendar/scheduling/planner applications, names are not unique to any time slot. The user are free to add any slot to any time unrestricted. For example, you can have lectures of same names across weeks and you can have two slots overlapping to accommodate conflicting meetings, double booked events that overlap, clashing classes, etc.
