### ISSUE TITLE
delete does not delete all related tags

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#170]
**Describe the bug**
I have added multiple slots with the same tag. However, when I try to delete the relevant tag, it only deleted 2 of them and not all.

**To Reproduce**
1. `add n/CS2113T Tutorial d/mon st/08:00 et/09:00 des/Topic: Sequence Diagram t/CS2113T t/Tutorial r/normal` add this 20 times
2. del t/CS2113T
3.   Deleted Slots:
 1.	CS2113T Tutorial, 2019-04-08 08:00, Week 12, MONDAY
 2.	CS2113T Tutorial, 2019-04-15 08:00, Week 13, MONDAY

**Expected behavior**
 1.	CS2113T Tutorial, 2019-04-08 08:00, Week 12, MONDAY
 2.	CS2113T Tutorial, 2019-04-15 08:00, Week 13, MONDAY
 3.	CS2113T Tutorial, 2019-04-08 08:00, Week 12, MONDAY
 4.	CS2113T Tutorial, 2019-04-15 08:00, Week 13, MONDAY
..... 20 times

<hr>

**Reported by:** @nicholasleeeee
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#103]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. This is indeed an issue. There seems to be an error in choosing the data structure used to store this list. A fix will be provided very shortly !

**Comment by seanieyap** [comment]
This bug has been fixed, the delete command now works as expected.
