### ISSUE TITLE
"Add" command allows user to add a slot that end time is earlier than start time.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#171]
**Describe the bug**
If I type the command "add n/CS2113T Tutorial d/mon st/10:00 et/09:00 des/Topic: Sequence Diagram t/CS2113T t/Tutorial r/normal", it will still be added to the planner, which shows the Duration is a negative value.

**Expected behavior**
"Add" command can not allow users to add a slot that the end time is earlier than the start time  

**Screenshots**
 
![image](https://user-images.githubusercontent.com/32561507/55453904-5b230d00-5610-11e9-9897-9247e94de94c.png)

![image](https://user-images.githubusercontent.com/32561507/55453896-54949580-5610-11e9-844e-8df080419ed0.png)

<hr>

**Reported by:** @wanchunwei
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#111]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. This case was indeed not considered during development. A fix will be provided very shortly !

**Comment by seanieyap** [comment]
This bug has been fixed, users are no longer allowed to add a slot with a negative duration.
