### ISSUE TITLE
User Guide not properly formatted

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#173]
**Describe the bug**
Headings for the user guide from the `clear` command onwards could be modified to display properly.  

**To Reproduce**
1. Go to UserGuide
2. Scroll down to `clear` command

**Expected behavior**
Proper headings should be displayed, but instead markdown is displayed.

<hr>

**Reported by:** @josephinetanadi
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#142]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback, There was a typo in the user guide causing this issue. This was spotted and fixed in #157.
