### ISSUE TITLE
unable to add slot with the correct date

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#174]
**Describe the bug**
Added the 3rd of April but showed that I added 10th April

**To Reproduce**
1. `add n/CS2113T Tutorial d/3/4/19 st/08:00 et/09:00`
2. look at the added slot

**Expected behavior**
add slot with the correct date

**Screenshots**
<img width="447" alt="Screen Shot 2019-04-03 at 1 10 51 PM" src="https://user-images.githubusercontent.com/35677197/55454347-2e6ff500-5612-11e9-845a-88f2933fe4d7.png">

<hr>

**Reported by:** @nicholasleeeee
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#173]</sub>

**Comment by seanieyap** [comment]
Hi, thank you for feedback.

However, the date format input here is incorrect and the system automatically assumed that the you would like to add to the nearest "3" which is a Wednesday, hence the result here is correct. This is the byproduct of the flexible and "auto-correction" system that we have implemented.
