### ISSUE TITLE
Diagrams in user guide not updated

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#176]
**Describe the bug**
Diagram at user guide (Section 4.1) does not reflect expected output of `help` command. Since output of `help` is shown, user might not execute the command itself and would be referring to the wrong list of commands. 

**To Reproduce**
1. Execute 'help'

**Expected behavior**
Diagram at help command should match output of executing help.

<hr>

**Reported by:** @josephinetanadi
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#200]</sub>

**Comment by seanieyap** [comment]
Hi,

Thank you for your feedback. Indeed this image was forgotten and not updated. This will be fixed soon !
