### ISSUE TITLE
View day command: Command format changed

### ISSUE THREAD

**Issue by marcus-pzj** [CS2113-AY1819S2-T08-3/main#189]
<img width="342" alt="Screenshot 2019-04-13 at 4 02 18 PM" src="https://user-images.githubusercontent.com/32394182/56076565-89b99880-5e05-11e9-8989-ae7645d9bf89.png">

Command format for view day dd/mm/yyyy has been changed to dd-mm-yyyy .

**Comment by dingheng4448** [comment]
Resolved as of #190
