### ISSUE TITLE
Photo uploaded

### ISSUE THREAD

**Issue by seanieyap** [CS2113-AY1819S2-T08-3/main#8]
a photo complying to the guidelines is in the master branch of the team repo.

- The purpose of the profile photo is for the teaching team to identify you. Therefore, you should choose a recent individual photo showing your face clearly (i.e., not too small) -- somewhat similar to a passport photo. Some examples can be seen in the 'Teaching team' page. Given below are some examples of good and bad profile photos.
- If you are uncomfortable posting your photo due to security reasons, you can post a lower resolution image so that it is hard for someone to misuse that image for fraudulent purposes. If you are concerned about privacy, you can request permission to omit your photo from the page by writing to prof.

**Comment by seanieyap** [comment]
@macchazuki Please send me a photo of yourself ! @dingheng4448 Should i use that photo?

**Comment by dingheng4448** [comment]
Yes, you can use that photo.

**Comment by seanieyap** [comment]
Photos have all been uploaded and updated as of #24
